SE1616_Group1_A3/Models/Show.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


#nullable disable

namespace SE1616_Group1_A3.Models
{
    public partial class Show
    {
        public int ShowId { get; set; }
        public int RoomId { get; set; }
        public int FilmId { get; set; }
        public DateTime? ShowDate { get; set; }
        [Range(1, 999999)]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18,2)")]


        public decimal? Price { get; set; }

        public bool? Status { get; set; }
        public int? Slot { get; set; }
    }
}

SE1616_Group1_A3/Controllers/ShowsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using SE1616_Group1_A3.Code;
using SE1616_Group1_A3.Models;

namespace SE1616_Group1_A3.Controllers
{
    public class ShowsController : Controller
    {
        private readonly CinemaContext _context;

        public ShowsController(CinemaContext context)
        {
            _context = context;
        }

        // GET: Shows

        private int?[] getSlotsByDateEdit(DateTime date, int roomId, int currentSlot)
        {
            int?[] a = { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
            int?[] slots = _context.Shows.Where(s => s.RoomId == roomId && s.ShowDate == date).Select(s => s.Slot).ToArray();
            foreach (int number in slots)
            {
                int numToRemove = number;
                if (numToRemove != currentSlot)
                    a = a.Where(val => val != numToRemove).ToArray();
            }
            return a;
        }
        public async Task<IActionResult> Index(Login user, Show show)
        {
            ViewBag.Film = _context.Films.ToList();
            ViewBag.Room = _context.Rooms.ToList();
           
            if (show.FilmId == 0)
            {
                ViewBag.Show = _context.Shows.ToList();
            }
            else
            {
                ViewBag.Show = _context.Shows.Where(x => x.FilmId == show.FilmId
                && x.RoomId == show.RoomId && x.ShowDate == show.ShowDate).ToList<Show>();
            }
            
            if (ModelState.IsValid)
            {
                string name, pass;
                var conf = new ConfigurationBuilder()
                    .SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile("appsettings.json", true, true)
                    .Build();
                name = conf["User:Name"];
                pass = conf["User:Password"];
                //HttpContext.Session.SetInt32("age", 20);
                //HttpContext.Session.SetString("username", "abc");                
                
                if (user.UserName.Equals(name) && user.Password.Equals(pass))
                {
                    Login lw = new Login(name, pass);
                    SessionHelper.SetObjectAsJson(HttpContext.Session, "User", lw);

                }
                else
                {
                    TempData["message"] = "User or Password is not correct";
                    return Redirect("/Home/Index");
                }
                

                
            }
            return View();


        }
       

        // GET: Shows/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows
                .FirstOrDefaultAsync(m => m.ShowId == id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // GET: Shows/Create
        public IActionResult Create(string dob,int room=1,int film=1)
        {
            if(dob == null)
            {
                dob = DateTime.Now.ToString("yyyy-MM-dd"); 
            }
            DateTime date = Convert.ToDateTime(dob);
            ViewBag.Film = _context.Films.ToList();
            ViewBag.Room = _context.Rooms.ToList();
            ViewBag.Show = _context.Shows.ToList();
            ViewBag.Slot = _context.Shows.Where(s=> s.ShowDate== date && s.RoomId==room && s.FilmId==film ).ToList();
            return View();
        }

        // POST: Shows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ShowId,RoomId,FilmId,ShowDate,Price,Status,Slot")] Show show)
        {
            if (ModelState.IsValid)
            {
                _context.Add(show);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(show);
        }

        // GET: Shows/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows.FindAsync(id);
            if (show == null)
            {
                return NotFound();
            }
            int?[] slots = getSlotsByDateEdit((DateTime)show.ShowDate, show.RoomId, (int)show.Slot);
            ViewData["FilmId"] = new SelectList(_context.Films, "FilmId", "Title", show.FilmId);
            ViewData["RoomId"] = new SelectList(_context.Rooms, "RoomId", "Name", show.RoomId);
            ViewData["slot"] = new SelectList(slots);
            return View(show);
        }

        // POST: Shows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ShowId,RoomId,FilmId,ShowDate,Price,Status,Slot")] Show show)
        {
            if (id != show.ShowId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(show);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShowExists(show.ShowId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FilmId"] = new SelectList(_context.Films, "FilmId", "CountryCode", show.FilmId);
            ViewData["RoomId"] = new SelectList(_context.Rooms, "RoomId", "RoomId", show.RoomId);
            return View(show);
        }

        // GET: Shows/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows
                .FirstOrDefaultAsync(m => m.ShowId == id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // POST: Shows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var show = await _context.Shows.FindAsync(id);
            _context.Shows.Remove(show);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShowExists(int id)
        {
            return _context.Shows.Any(e => e.ShowId == id);
        }
    }
}

SE1616_Group1_A3/Views/Shows/Create.cshtml
@model SE1616_Group1_A3.Models.Show

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Show</h4>
<hr />
<div class="row">
    <div class="col-md-4">
       
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label"></label>
                <select id="room" asp-for="RoomId"  class="form-control"  asp-items="@(new SelectList(ViewBag.Room,"RoomId","Name"))" ></select>
                <span asp-validation-for="RoomId" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="ShowDate" class="control-label"></label>
                <input id="dob" type="date" asp-for="ShowDate" class="form-control" value="@DateTime.Now.ToString("yyyy-MM-dd")" />
                <span asp-validation-for="ShowDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FilmId" class="control-label"></label>
                <select id="film" asp-for="FilmId"  class="form-control"  asp-items="@(new SelectList(ViewBag.Film,"FilmId","Title"))" ></select>
                <span asp-validation-for="FilmId" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Slot" class="control-label"></label>
               <select  asp-for="Slot"  class="form-control"  >                  
                    @{
                        List<int> list = new List<int>
                        {
                            1,2,3,4,5,6,7,8,9,10
                        };
                        foreach (var item in ViewBag.Slot as List<Show>)
                        {
                            string re = @item.Slot.ToString();
                            list.Remove(Convert.ToInt32(re));
                        }
                        foreach (var i in list)
                        {
                            <option value="@i">@i</option>
                        }
                                 
                            

                         
                    }
               </select>
                <span asp-validation-for="Slot" class="text-danger"></span>
            </div>
            
           
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input type="text" name="Price"  class="form-control"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<script type="text/javascript">

   $('#room').on('change', function () {
     var room = $("#room option:selected").val();
    var film = $("#film option:selected").val();
    var d = new Date();
    let month = (d.getMonth()+1);
    if(month < 10){
        month = "0"+month;
    }
    let day =d.getDate();
    if(day < 10){
        day = "0"+day;
    }
    var strDate = d.getFullYear() + "-" + month + "-" + day;
    window.location.href="/Shows/Create?dob="+strDate+"&&room="+ room+"&&film="+film;
    
});
$('#dob').on('change', function () {
    var room = $("#room option:selected").val();
    var film = $("#film option:selected").val();
    //alert("/Shows/Create?dob="+$(this).val()+"&&room="+ room+"&&film="+film);
     window.location.href="/Shows/Create?dob="+$(this).val()+"&&room="+ room+"&&film="+film;
});
$('#film').on('change', function () {
    var room = $("#room option:selected").val();
    var film = $("#film option:selected").val();
    var d = new Date();
    let month = (d.getMonth()+1);
    if(month < 10){
        month = "0"+month;
    }
    let day =d.getDate();
    if(day < 10){
        day = "0"+day;
    }
    var strDate = d.getFullYear() + "-" + month + "-" + day;
     window.location.href="/Shows/Create?dob="+strDate+"&&room="+ room+"&&film="+film;
});
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SE1616_Group1_A3/Views/Shows/Delete.cshtml
@model SE1616_Group1_A3.Models.Show

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Show</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoomId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoomId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilmId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilmId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShowDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShowDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Slot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Slot)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ShowId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SE1616_Group1_A3/Views/Shows/Details.cshtml
@model SE1616_Group1_A3.Models.Show

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Show</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoomId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoomId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilmId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilmId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShowDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShowDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Slot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Slot)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ShowId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SE1616_Group1_A3/Views/Shows/Edit.cshtml
@model SE1616_Group1_A3.Models.Show

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Show</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ShowId" />
            <div class="form-group">
                <label asp-for="RoomId" class="control-label"></label>
                <input asp-for="RoomId" class="form-control" />
                <span asp-validation-for="RoomId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FilmId" class="control-label"></label>
                <input asp-for="FilmId" class="form-control" />
                <span asp-validation-for="FilmId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShowDate" class="control-label"></label>
                <input asp-for="ShowDate" class="form-control" />
                <span asp-validation-for="ShowDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                
                <input type="text" value="@Model.Price" name="Price" class="form-control"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status"  data-val="false"  class="form-control" />
                
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Slot" class="control-label"></label>
                <select asp-for="Slot" class="form-control" asp-items="ViewBag.slot"></select>
                <span asp-validation-for="Slot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SE1616_Group1_A3/Views/Shows/Index.cshtml
@model SE1616_Group1_A3.Models.Show

@{
    ViewData["Title"] = "Index";

}
@using SE1616_Group1_A3.Models
@using Microsoft.AspNetCore.Http
@using SE1616_Group1_A3.Code


<h1>Show</h1>
<form asp-controller="Shows" asp-action="Index">
    <div class="col-md-4">
<label >Film:</label>
<select asp-for="FilmId" class="form-control"  asp-items="@(new SelectList(ViewBag.Film,"FilmId","Title"))"></select>
    </div>
    <div class="col-md-4">
        <label >Date:</label>
<input asp-for="ShowDate" class="form-control"  type="date" value="@DateTime.Now.ToString("yyyy-MM-dd")"/>
    </div>
 <div class="col-md-4">
     <label >Room:</label>
<select asp-for="RoomId" class="form-control"   asp-items="@(new SelectList(ViewBag.Room,"RoomId","Name"))"></select>
<input type="submit" value="Search" class="btn btn-primary"/>
 </div>

</form>
@{
        Login login = SessionHelper.GetObjectFromJson<Login>(Context.Session, "User");
    }

<p>
    <a style="@(login==null?"display:none;":"")" asp-action="Create">Create New</a>
</p>
@{
    int count = (ViewBag.Show as List<Show>).Count;
}
<h2>The number of shows: @count</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RoomId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FilmId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShowDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Slot)
            </th>
            <th >
                Booking
            </th>
            <th style=@(login==null?"display:none;":"")>
                Edit
            </th>
            <th style=@(login==null?"display:none;":"")>
                Delete
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in ViewBag.Show as List<Show>) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RoomId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FilmId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShowDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Slot)
            </td>
           
            <td>              
                <a  href="/Bookings/Index/@item.ShowId">Booking</a> 
            </td>
             <td style=@(login==null?"display:none;":"")>
                <a asp-action="Edit" asp-route-id="@item.ShowId">Edit</a>         
            </td>
            <td style=@(login==null?"display:none;":"")>
                <a asp-action="Delete" asp-route-id="@item.ShowId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>